### ISSUE TITLE
Tank targets own corpse while fighting

### ISSUE THREAD

**Issue by towbes** [aquietone/aqobot#24]
While engaged with a target and active targets on xtarget list, if the tank has a corpse nearby, they will target their corpse for a split second before going back over to the tanking target. If they are supposed to be looting it during this time there might be another issue where my ping is too high for the action to take place

**Comment by aquietone** [comment]
did you call the tank or something?
if it sees your corpse nearby, it cons it to see if its been rezzed, and if so then would try to loot it. since you don't seem to be trying to loot it, guessing its not rezzed?
updated the check to not bother checking if the corpse has been rezzed if autoattack is on or combat state is combat.. hopefully this doesn't prevent toons rezzed in combat from trying to loot their corpses, guess we'll see.

**Comment by towbes** [comment]
Ah yes I probably ran back to camp rather than getting rezzed in this situation so was fighting on top of a non rezzed corpse.

**Comment by towbes** [comment]
This is a bit of a hard situation to set up, but I think my tank has been looting corpse before going into engage if they are rezzed mid combat..

**Comment by towbes** [comment]
Confirmed that tank is looting corpse before engaging after getting rezzed in combat so this should be all good
