### ISSUE TITLE
Return to Camp

### ISSUE THREAD

**Issue by Kausaliax** [aquietone/aqobot#29]
When I click Return to Camp, my toon does nothing.  

Along those lines, is there a setting that will make the toon go to his camp spot after killing a mob?  Right now if they are within the camp radius they stay in that spot until another mob comes inside the radius.

**Comment by aquietone** [comment]
Changed the logic a little bit.
Return To Camp button should force return to camp center now. Although its only for the toon, its not broadcasting anything.. may change that.
If mobs are in camp toons won't try to return to camp unless they are > 15 beyond the camp radius, so that if they end up fighting around the edge they aren't trying to run back in mid fight.
If no mobs in camp, toons return to camp if further than campradius/2 away from camp center.
